### ISSUE TITLE
Filter by Key is not working.

### ISSUE THREAD

**Issue by Spawn** [Bogdanp/anom-py#4]
When I try:
`list(Subscriber.query().select().where(Subscriber.account == account).run())`
It cause an error:
```
Traceback (most recent call last):
  File "/home/bogdan/Projects/inkit-public-api/.env/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/bogdan/Projects/inkit-public-api/.env/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/bogdan/Projects/inkit-public-api/.env/lib/python3.6/site-packages/falcon/api.py", line 242, in __call__
    responder(req, resp, **params)
  File "/home/bogdan/Projects/inkit-public-api/controllers/subscribers.py", line 20, in on_get
    subscribers = self.get_subscribers(account)
  File "/home/bogdan/Projects/inkit-public-api/controllers/subscribers.py", line 64, in get_subscribers
    subscribers = list(Subscriber.query().select().where(Subscriber.account == account).run())
  File "/home/bogdan/Projects/inkit-public-api/.env/lib/python3.6/site-packages/anom/query.py", line 105, in __next__
    return next(self._entities)
  File "/home/bogdan/Projects/inkit-public-api/.env/lib/python3.6/site-packages/anom/query.py", line 139, in _get_entities
    for batch in self._get_batches():
  File "/home/bogdan/Projects/inkit-public-api/.env/lib/python3.6/site-packages/anom/query.py", line 113, in _get_batches
    entities, self._options.cursor = adapter.query(self._query, self._options)
  File "/home/bogdan/Projects/inkit-public-api/.env/lib/python3.6/site-packages/anom/adapters/datastore_adapter.py", line 189, in query
    for entity in result_iterator:
  File "/home/bogdan/Projects/inkit-public-api/.env/lib/python3.6/site-packages/google/cloud/iterator.py", line 218, in _items_iter
    for page in self._page_iter(increment=False):
  File "/home/bogdan/Projects/inkit-public-api/.env/lib/python3.6/site-packages/google/cloud/iterator.py", line 247, in _page_iter
    page = self._next_page()
  File "/home/bogdan/Projects/inkit-public-api/.env/lib/python3.6/site-packages/google/cloud/datastore/query.py", line 482, in _next_page
    query_pb = self._build_protobuf()
  File "/home/bogdan/Projects/inkit-public-api/.env/lib/python3.6/site-packages/google/cloud/datastore/query.py", line 424, in _build_protobuf
    pb = _pb_from_query(self._query)
  File "/home/bogdan/Projects/inkit-public-api/.env/lib/python3.6/site-packages/google/cloud/datastore/query.py", line 547, in _pb_from_query
    helpers._set_protobuf_value(property_filter.value, value)
  File "/home/bogdan/Projects/inkit-public-api/.env/lib/python3.6/site-packages/google/cloud/datastore/helpers.py", line 408, in _set_protobuf_value
    attr, val = _pb_attr_value(val)
  File "/home/bogdan/Projects/inkit-public-api/.env/lib/python3.6/site-packages/google/cloud/datastore/helpers.py", line 325, in _pb_attr_value
    raise ValueError("Unknown protobuf attr type %s" % type(val))
ValueError: Unknown protobuf attr type <class 'anom.model.Key'>
```
Account model:

```
class Account(Model):
    name = props.String()
    api_token = props.String(indexed=True)
```

Subscriber model:
```
class Subscriber(Model):
    source = props.String(indexed=True)
    account = props.Key(kind="Account", indexed=True)
    tags = props.Key(repeated=True, kind="Tag")
    first_name = props.String(indexed=True)
    last_name = props.String(indexed=True)
    company = props.String(optional=True)
```

**Comment by Bogdanp** [comment]
Thanks! I'll fix this sometime this weekend.

**Comment by Spawn** [comment]
https://github.com/Bogdanp/anom-py/pull/6/files
