### ISSUE TITLE
Repeated is not working.

### ISSUE THREAD

**Issue by Spawn** [Bogdanp/anom-py#5]
Got an error:
```Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/bogdan/Projects/inkit-public-api/.env/lib/python3.6/site-packages/anom/model.py", line 432, in __init__
    setattr(self, name, value)
  File "/home/bogdan/Projects/inkit-public-api/.env/lib/python3.6/site-packages/anom/model.py", line 300, in __set__
    ob._data[self.name_on_entity] = self.validate(value)
  File "/home/bogdan/Projects/inkit-public-api/.env/lib/python3.6/site-packages/anom/properties.py", line 498, in validate
    raise ValueError(f"Property {self.name_on_model} cannot be assigned keys of kind {value.kind}.")
ValueError: Property tags cannot be assigned keys of kind Key('Tag', 5073368378245120, parent=None, namespace=None).
```
When try:
`s = Subscriber(account=a, tags=(t.key, t1.key), first_name="Bob", last_name="Bobbson", address=addr, source="manual")`
Where t and t1 - Tag objects.

Model:
```
class Subscriber(Model):

    # immutable
    source = props.String(indexed=True)
    account = props.Key(kind="Account", indexed=True)
    tags = props.Key(repeated=True, kind="Tag")

    # mutable
    first_name = props.String(indexed=True)
    last_name = props.String(indexed=True)
    company = props.String(optional=True)
```

What am I doing wrong?

**Comment by Spawn** [comment]
Still have an issue.

```>>>from models.anom_models import Subscriber
>>>from models.anom_models import Address
>>>from models.anom_models import Tag
>>>from models.anom_models import Account
>>>a = Address(address_line1='test', city='city', state='ST', country='CN', zip='12321')
>>>acc = Account.get(5707702298738688 )
>>>t = Tag(name='kek')
>>>t1 = Tag(name='kekses')
>>>t.put()
Tag(key=Key('Tag', 5137785908363264, parent=None, namespace=None), account=[], name='kek', created=datetime.datetime(2017, 11, 6, 16, 39, 26, 25807, tzinfo=tzutc()), updated=datetime.datetime(2017, 11, 6, 16, 39, 26, 26089, tzinfo=tzutc()), deleted=None)
>>>t1.put()
Tag(key=Key('Tag', 5690145009303552, parent=None, namespace=None), account=[], name='kekses', created=datetime.datetime(2017, 11, 6, 16, 39, 30, 140522, tzinfo=tzutc()), updated=datetime.datetime(2017, 11, 6, 16, 39, 30, 140766, tzinfo=tzutc()), deleted=None)
>>>s = Subscriber(account=acc, tags=(t.key, t1.key), first_name='bob', last_name='kok', address=a)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/bogdan/Projects/inkit-public-api/.env/lib/python3.6/site-packages/anom/model.py", line 433, in __init__
    setattr(self, name, value)
  File "/home/bogdan/Projects/inkit-public-api/.env/lib/python3.6/site-packages/anom/model.py", line 301, in __set__
    ob._data[self.name_on_entity] = self.validate(value)
  File "/home/bogdan/Projects/inkit-public-api/.env/lib/python3.6/site-packages/anom/properties.py", line 503, in validate
    raise ValueError(f"Property {self.name_on_model} cannot be assigned keys of kind {value.kind}.")
ValueError: Property tags cannot be assigned keys of kind Key('Tag', 5137785908363264, parent=None, namespace=None).
```

**Comment by Bogdanp** [comment]
Use a list instead:

```
s = Subscriber(account=acc, tags=[t.key, t1.key], first_name='bob', last_name='kok', address=a)
```
